//  - Represent a "scene" as a reusable asset (LevelAsset)
//  - Instantiate it into a runtime Scene (LevelInstance)
//  - Keep RHI bindings (descriptor indices) as a runtime concern
//
// Input format:
//  - JSON file (*.level.json). The schema is intentionally simple and stable.
//  - It can be generated by external tools (e.g. Blender exporter) or edited by hand.

namespace
{
	using jsonUtils::JsonArray;
	using jsonUtils::JsonObject;
	using jsonUtils::JsonParser;
	using jsonUtils::JsonValue;
	using jsonUtils::GetBoolOpt;
	using jsonUtils::GetFloatOpt;
	using jsonUtils::GetIntOpt;
	using jsonUtils::GetReq;
	using jsonUtils::GetStringOpt;
	using jsonUtils::ReadFloatArray;
	using jsonUtils::SortedStringKeys;
	using jsonUtils::TryGet;
	using jsonUtils::WriteJsonBool;
	using jsonUtils::WriteJsonEscaped;
	using jsonUtils::WriteJsonFloat;
	using jsonUtils::WriteJsonMat4ColMajor16;
	using jsonUtils::WriteJsonVec3;
	using jsonUtils::WriteJsonVec4;

	mathUtils::Mat4 ReadMat4_ColumnMajor16(const JsonValue& v, std::string_view what)
	{
		return jsonUtils::ReadMat4ColumnMajor16(v, what);
	}

	rendern::EnvSource ParseEnvSourceOrThrow(const JsonValue& v, std::string_view materialId)
	{
		if (!v.IsString())
		{
			throw std::runtime_error("Level JSON: materials." + std::string(materialId) + ".envSource must be a string");
		}

		const std::string s = stringUtils::ToLowerAsciiCopy(v.AsString());
		if (s == "skybox")
		{
			return rendern::EnvSource::Skybox;
		}
		if (s == "reflectioncapture" || s == "reflection_capture" || s == "capture")
		{
			return rendern::EnvSource::ReflectionCapture;
		}

		throw std::runtime_error(
			"Level JSON: materials." + std::string(materialId) + ".envSource must be skybox|reflectionCapture");
	}

	rendern::MaterialPerm ParsePermFlags(const JsonValue& v)
	{
		if (!v.IsArray())
		{
			throw std::runtime_error("Level JSON: material.flags must be array");
		}
		rendern::MaterialPerm flags = rendern::MaterialPerm::None;

		for (const auto& it : v.AsArray())
		{
			if (!it.IsString())
			{
				throw std::runtime_error("Level JSON: material.flags entries must be strings");
			}
			const std::string& s = it.AsString();
			const std::string norm = stringUtils::ToLowerAsciiCopy(s);
			if (norm == "useshadow" || norm == "use_shadow") flags |= rendern::MaterialPerm::UseShadow;
			else if (norm == "transparent") flags |= rendern::MaterialPerm::Transparent;
			else if (norm == "skinning") flags |= rendern::MaterialPerm::Skinning;
			else if (norm == "usetex" || norm == "use_tex") flags |= rendern::MaterialPerm::UseTex; // usually inferred
			else if (norm == "planarmirror" || norm == "planar_mirror" || norm == "planar") flags |= rendern::MaterialPerm::PlanarMirror;
			else
			{
				throw std::runtime_error("Level JSON: unknown material flag: " + s);
			}
		}
		return flags;
	}


}
