#include "RendererImpl/DirectX12Renderer_RenderFrame_01_BuildInstances_ShadowAndLayeredShadow.inl"
#include "RendererImpl/DirectX12Renderer_RenderFrame_01_BuildInstances_MainTransparentReflectionPacking.inl"
#include "RendererImpl/DirectX12Renderer_RenderFrame_01_BuildInstances_FinalizeAndUpload.inl"